In [82]:
import pandas as pd
import numpy as np
import math

In [83]:
#read data and transfer the data into matrix
def read_data(file_path):
    max_user_id = 0
    max_movie_id = 0
    
    with open(file_path, 'r') as file:
        for line in file:
            #split each row data in train text and map the values to matrix
            user_id, movie_id, rating = map(int, line.split())
            if user_id > max_user_id:
                max_user_id = user_id
            if movie_id > max_movie_id:
                max_movie_id = movie_id
    
    # create a matrix of U-M and set dimension to (max_user_id, max_movie_id)
    user_movie_matrix = np.zeros((max_user_id, max_movie_id))
    
    # fill the matrix
    with open(file_path, 'r') as file:
        for line in file:
            user_id, movie_id, rating = map(int, line.split())
            user_movie_matrix[user_id-1, movie_id-1] = rating
    
    return user_movie_matrix, max_user_id, max_movie_id

train_file_path = "E:\\文档\\AA-SCU\\272\\Proj 2\\train.txt"
user_movie_matrix, max_user_id, max_movie_id = read_data(train_file_path)
# transfer the numpy list into dataframe
df = pd.DataFrame(user_movie_matrix, columns=[str(i) for i in range(user_movie_matrix.shape[1])])



In [84]:
df

0    1    2    3    4    5    6    7    8    9  ...  990  991  992  \
0    5.0  3.0  0.0  3.0  3.0  5.0  0.0  1.0  5.0  3.0  ...  0.0  0.0  0.0   
1    4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    4.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  ...  0.0  0.0  0.0   
196  0.0  3.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
197  4.0  0.0  0.0  3.0  0.0  2.0  4.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198  1.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  5.0  0.0  ...  0.0  0.0  0.0   
199  5.0  4.0  0.0  0.0  0.0  0.0  4.0  4.0  4.0  0.0  ...  0.0  0.0  0.0   

     993  994  995  996  997  998  999  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
196  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
197  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
199  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[200 rows x 1000 columns]

In [85]:
arr = df.to_numpy()
print(arr)
print(arr.shape)

[[5. 3. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [5. 4. 0. ... 0. 0. 0.]]
(200, 1000)


In [86]:
#read the test data
test5 = pd.read_csv('E:\\文档\AA-SCU\\272\\Proj 2\\test5.txt', sep=" ", header=None)
test10 = pd.read_csv('E:\\文档\AA-SCU\\272\\Proj 2\\test10.txt', sep=" ", header=None)
test20 = pd.read_csv('E:\\文档\\AA-SCU\\272\\Proj 2\\test20.txt', sep=" ", header=None)

In [87]:
#Create a list(1x1000) for each test users.
#To Match the dimensions of the training data lists(200x1000)

def create_matrix_for_new_users(exist_ratings, test_file):
    init_ratings = [0] * 1000
    test_users = {}
    ratings = init_ratings
    count = 0
    for index,row in test_file.iterrows():
        #test file data: 201 237 4
        if row[2] == 0:
            continue;
        user = row[0]
        index = row[1]-1
        rating = row[2]
        ratings[index] = rating
        count += 1
        if count == exist_ratings:
            test_users[user] = ratings
            ratings = [0] * 1000
            count = 0
    return test_users



In [88]:
#Create test_user matrix
test5_user_arr = create_matrix_for_new_users(5, test5)
test10_user_arr = create_matrix_for_new_users(10, test10)
test20_user_arr = create_matrix_for_new_users(20, test20)

In [89]:
print_dimensions_test_arr(test5_user_arr, 201)
print_dimensions_test_arr(test10_user_arr, 301)
print_dimensions_test_arr(test20_user_arr, 401)

Rows: 100, Columns: 1000
Rows: 100, Columns: 1000
Rows: 100, Columns: 1000


In [369]:
print(test5_user_arr)

{201: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 

In [450]:
#Cosine Similarity
def updated_cos_sim(v1, v2):
    v1_new = []
    v2_new = []
    for index in range(len(v1)):
        if v1[index] != 0 and v2[index] != 0:
            v1_new.append(v1[index])
            v2_new.append(v2[index])
    #No similar dimenions between users, set sim==0
    if(len(v1_new) == 0 and len(v2_new) == 0):
        sim = 0
        return sim
    """
    #Only 1 dimension that is similar between the two users
    #set sim==inverse euclidean distance
    if(len(v1_new) == 1 and len(v2_new) == 1):
        euclidean_distance = np.linalg.norm(v1_new[0]-v2_new[0])
        sim = 1/(1+euclidean_distance)
        return sim

    """

    
    numerator = np.dot(v1_new,v2_new)
    v1_norm = np.sqrt(np.sum(np.square(v1_new)))
    v2_norm = np.sqrt(np.sum(np.square(v2_new)))
    #calculate the cosine similarity 
    sim = numerator/(v1_norm * v2_norm)
    
    return sim

In [451]:
#Calculating the cos_sim for each active user with every single user in the training data. 
#Row 0 is the list of similarities between active user 201 with users 1-200
#Matrix Dimensions: 100x200

def create_cos_sim_matrix(matrix, users_arr, training_arr):
    count = 0
    matrix = []
    vals = []
    for key in users_arr:
        for row in training_arr:
            cos_sim_value = updated_cos_sim(users_arr[key],row)
            vals.append(cos_sim_value)
            count += 1
            if count == 200:
                matrix.append(vals)
                vals = []
                count = 0
    return matrix

def print_matrix_dimensions(matrix):
    print("Rows: " + str(len(matrix)))
    print("Columns: " + str(len(matrix[0])) + "\n")

In [452]:
cos_sim_matrix_5 = pd.DataFrame()
cos_sim_matrix_10 = pd.DataFrame()
cos_sim_matrix_20 = pd.DataFrame()

In [453]:
cos_sim_matrix_5 = create_cos_sim_matrix(cos_sim_matrix_5, test5_user_arr, arr)
cos_sim_matrix_10 = create_cos_sim_matrix(cos_sim_matrix_10, test10_user_arr, arr)
cos_sim_matrix_20 = create_cos_sim_matrix(cos_sim_matrix_20, test20_user_arr, arr)

In [454]:
#Returns the list of matrix(100x200) of indexes with the highest cosine similarity in ascending order
import heapq
def top_k_sim(matrix,k=200):
    max_index = []
    for users in matrix:# 遍历每个活跃用户的余弦相似度列表
        abs_cos_sim = np.abs(users)  # 计算当前用户所有相似度的绝对值
        top_k_indices = heapq.nlargest(k, range(len(abs_cos_sim)), key=abs_cos_sim.__getitem__)  # 获取相似度最高的 k 个索引
        max_index.append(top_k_indices)  # 将这些索引添加到结果列表中
    return max_index  # 返回包含所有活跃用户相似度最高的 k 个用户索引的列表

top_k_5 = top_k_sim(cos_sim_matrix_5,k=200)
top_k_10 = top_k_sim(cos_sim_matrix_10,k=200)
top_k_20 = top_k_sim(cos_sim_matrix_20,k=200)

In [455]:
print(top_k_5[0], "\n")
print(top_k_10[0], "\n")
print(top_k_20[0], "\n")

[5, 10, 15, 16, 17, 18, 19, 23, 25, 28, 30, 31, 35, 38, 39, 42, 43, 47, 48, 49, 51, 53, 55, 56, 57, 58, 60, 61, 63, 65, 67, 72, 73, 74, 76, 77, 79, 80, 83, 88, 90, 93, 94, 99, 100, 104, 106, 107, 108, 114, 116, 119, 120, 126, 135, 136, 138, 139, 140, 142, 143, 145, 148, 149, 151, 154, 158, 159, 161, 166, 168, 173, 176, 177, 178, 181, 182, 183, 184, 187, 190, 193, 195, 197, 198, 78, 46, 84, 112, 62, 103, 172, 1, 41, 89, 111, 118, 68, 175, 2, 170, 185, 14, 163, 115, 127, 192, 129, 0, 12, 128, 188, 91, 98, 6, 156, 44, 180, 144, 3, 4, 7, 8, 9, 11, 13, 20, 21, 22, 24, 26, 27, 29, 32, 33, 34, 36, 37, 40, 45, 50, 52, 54, 59, 64, 66, 69, 70, 71, 75, 81, 82, 85, 86, 87, 92, 95, 96, 97, 101, 102, 105, 109, 110, 113, 117, 121, 122, 123, 124, 125, 130, 131, 132, 133, 134, 137, 141, 146, 147, 150, 152, 153, 155, 157, 160, 162, 164, 165, 167, 169, 171, 174, 179, 186, 189, 191, 194, 196, 199] 

[19, 65, 123, 2, 3, 18, 20, 26, 28, 30, 32, 36, 37, 38, 44, 46, 49, 51, 52, 60, 66, 73, 74, 80, 86, 87, 88,

In [541]:
def weighted_rating_cos_sim(test_file, shift_index, top_k, cos_sim_matrix, default_k, sim_threshold=0.6):
    output = []
    
    for index, row in test_file.iterrows():
        #Only rating when the current rating is 0
        if row[2] == 0: 
            numerator = 0
            denominator = 0
            temp_counter = 0
            user_id = row[0] - shift_index
            movie_id = row[1] - 1
            
            indexes = top_k[user_id]
            reverse_indexes = indexes.copy()
            reverse_indexes.reverse()
            
            for ind in reverse_indexes:
                cos_sim = cos_sim_matrix[user_id][ind]
                ranking = arr[ind][movie_id]  # 假设 arr 是一个全局变量或传入的参数，表示用户-电影评分矩阵
                
                if ranking != 0 and cos_sim > sim_threshold:
                    temp_counter += 1
                    numerator += (cos_sim * ranking)
                    denominator += cos_sim
                    
                    if temp_counter == default_k:
                        break

            if numerator != 0 and denominator != 0:
                final_rank = numerator / denominator
                final_rank = int(round(final_rank, 0))
                line = [row[0], row[1], final_rank]
                output.append(line)
            else:
                line = [row[0], row[1], 3]  # 默认评分为3
                output.append(line)
            
            # 打印用户实际找到的相似用户数量用于调试
            if temp_counter >= 95:
                print(f"User {row[0]} has {temp_counter} similar users considered.")
    
    return output



In [542]:
output5 =  weighted_rating_cos_sim(test5, 201, top_k_5, cos_sim_matrix_5, 95)

In [543]:
output10 =  weighted_rating_cos_sim(test10, 301, top_k_10, cos_sim_matrix_10, 100)

User 320 has 97 similar users considered.
User 345 has 95 similar users considered.


In [544]:
output20 = weighted_rating_cos_sim(test20, 401, top_k_20, cos_sim_matrix_20, 150)

User 407 has 96 similar users considered.
User 407 has 98 similar users considered.
User 411 has 97 similar users considered.
User 414 has 95 similar users considered.
User 423 has 95 similar users considered.
User 424 has 98 similar users considered.
User 430 has 97 similar users considered.
User 439 has 98 similar users considered.
User 440 has 97 similar users considered.
User 444 has 97 similar users considered.
User 447 has 95 similar users considered.
User 456 has 101 similar users considered.
User 465 has 95 similar users considered.
User 466 has 96 similar users considered.
User 469 has 96 similar users considered.
User 473 has 95 similar users considered.
User 498 has 95 similar users considered.


In [99]:
def convert_list_to_str(line):
    string = str(line)[1:-1]
    string = string.replace(',', '')
    return string

In [100]:
def write_to_file(output, output_file):
    with open(output_file, 'w') as f:
        for line in output:
            f.write(convert_list_to_str(line))
            f.write('\n')

In [101]:
write_to_file(output5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_cos_result5.txt')
write_to_file(output10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_cos_result10.txt')
write_to_file(output20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_cos_result20.txt')

In [178]:
"""
Pearson Correlation
"""

'\nPearson Correlation\n'

In [179]:
def calculate_pearson_adjusted_ratings(user_ratings_matrix):
    adjusted_train_ratings_matrix = []  # 存储经过均值调整后的评分矩阵
    train_user_means = []  # 存储每个用户的评分均值

    for user_ratings in user_ratings_matrix:  # 遍历每个用户的评分
        non_zero_ratings = [rating for rating in user_ratings if rating != 0]
        if non_zero_ratings:
            mean_rating = sum(non_zero_ratings) / len(non_zero_ratings)
        else:
            mean_rating = 0
        
        train_user_means.append(mean_rating)
        
        adjusted_ratings = [(rating - mean_rating) if rating != 0 else 0 for rating in user_ratings]
        adjusted_train_ratings_matrix.append(adjusted_ratings)

    return adjusted_train_ratings_matrix, train_user_means


In [180]:
pearson_train_arr,pearson_train_means=calculate_pearson_adjusted_ratings(arr)
#print(pearson_train)
#print(pearson_means)

print("Rows of pearson_train: " + str(len(pearson_train_arr)))
print("Cols of pearson_train: " + str(len(pearson_train_arr[0])))
print("Length of train_pearson_means: " + str(len(pearson_train_means)))



Rows of pearson_train: 200
Cols of pearson_train: 1000
Length of train_pearson_means: 200


In [181]:
def calculate_pearson_adjusted_ratings_for_test(test_user_ratings_dict):
    adjusted_test_ratings_matrix = []
    test_user_means = []

    for user_id, user_ratings in test_user_ratings_dict.items():
        non_zero_ratings = [rating for rating in user_ratings if rating != 0]
        if non_zero_ratings:
            mean_rating = sum(non_zero_ratings) / len(non_zero_ratings)
        else:
            mean_rating = 0
        
        test_user_means.append(mean_rating)
        
        adjusted_ratings = [(rating - mean_rating) if rating != 0 else 0 for rating in user_ratings]
        adjusted_test_ratings_matrix.append(adjusted_ratings)
        
        # 更新用户评分字典
        test_user_ratings_dict[user_id] = adjusted_ratings

    return adjusted_test_ratings_matrix, test_user_means


In [191]:
pearson_test_5 = test5_user_arr.copy()
pearson_test_10= test10_user_arr.copy()
pearson_test_20 = test20_user_arr.copy()

pearson_test_5_arr, pearson_test_5_means = calculate_pearson_adjusted_ratings_for_test(pearson_test_5)
pearson_test_10_arr, pearson_test_10_means = calculate_pearson_adjusted_ratings_for_test(pearson_test_10)
pearson_test_20_arr, pearson_test_20_means = calculate_pearson_adjusted_ratings_for_test(pearson_test_20)

In [192]:
pearson_matrix_5 = pd.DataFrame()
pearson_matrix_10 = pd.DataFrame()
pearson_matrix_20 = pd.DataFrame()

In [195]:
pearson_matrix_5 =create_cos_sim_matrix(pearson_matrix_5, pearson_test_5,pearson_train_arr)
pearson_matrix_10 =create_cos_sim_matrix(pearson_matrix_10, pearson_test_10, pearson_train_arr)
pearson_matrix_20 =create_cos_sim_matrix(pearson_matrix_20, pearson_test_20, pearson_train_arr)
"""
print_matrix_dimensions(pearson_matrix_5)
print_matrix_dimensions(pearson_matrix_10)
print_matrix_dimensions(pearson_matrix_20)


"""
print(pearson_matrix_5)

[[0.8832792199852482, -0.5144957554275263, 0.8371662000158874, 0, 0, -1.0, -0.8852231639223185, 0, 0, 0, -0.09307041363593903, 0, -0.7561645013152865, 0, 0.27784410485078115, -1.0, 1.0, 1.0, -1.0, 1.0, 0, 0, 0, 1.0, 0, -1.0, 0, 0, 1.0, 0, -0.9999999999999999, 1.0, 0, 0, 0, -1.0, 0, 0, -1.0, 1.0, 0, -0.5144957554275263, -1.0, 1.0, -0.39872611141445014, 0, 0.9999999999999999, 1.0, 1.0, 1.0, 0, 1.0, 0, 0.08450232778878462, 0, -1.0, -1.0, 0.19458851485113338, 1.0, 0, -1.0, 1.0, 0.27216552697590846, -1.0, 0, -1.0, 0, -1.0, 0.7516256890704235, 0, 0, 0, -1.0, -1.0, 1.0, 0, 1.0, -1.0, 0.9999999999999999, -1.0, -1.0, 0, 0, -1.0, 0.924406524103778, 0, 0, 0, 1.0, 0.5144957554275262, 1.0, -0.4820657112104792, 0, 1.0, 1.0, 0, 0, 0, -0.9929546911750412, -1.0, -1.0, 0, 0, -0.2721655269759083, 1.0, 0, 1.0, 1.0, -1.0, 0, 0, 0.875387052861874, 0.9582506206705671, 0, 1.0, 0.5170926890922268, 0.2718091136800729, 0, -0.5144957554275263, 1.0, -1.0, 0, 0, 0, 0, 0, -1.0, -0.6300408568675976, -0.91578820879394

In [196]:
pearson_top_k_5 = top_k_sim(pearson_matrix_5)
pearson_top_k_10 = top_k_sim(pearson_matrix_10)
pearson_top_k_20 = top_k_sim(pearson_matrix_20)

print_matrix_dimensions(pearson_top_k_5)
print_matrix_dimensions(pearson_top_k_10)
print_matrix_dimensions(pearson_top_k_20)

Rows: 100
Columns: 200

Rows: 100
Columns: 200

Rows: 100
Columns: 200



In [209]:
def weighted_rating_pearson_correlation(test_data, shift_index,top_k_sim, cos_sim_matrix, test_user_means, train_user_means, ratings_matrix, k):
    output = []

    for index, row in test_data.iterrows():
        #filtering those unrated movies
        if row[2] == 0:
            active_user_id = row[0] - shift_index
            movie_id = row[1] - 1

            indexes = top_k_sim[active_user_id]
            reverse_indexes = indexes[::-1]

            numerator = 0
            denominator = 0
            counter = 0

            test_mean_val = test_user_means[active_user_id]

            for ind in reverse_indexes:
                mean_val_train_user = train_user_means[ind]
                cos_sim = cos_sim_matrix[active_user_id][ind]  # 修正为直接索引
                rating = ratings_matrix[ind][movie_id]

                if rating != 0:
                    numerator += cos_sim * (rating - mean_val_train_user)
                    denominator += abs(cos_sim)
                    counter += 1

                    if counter == k:
                        break
            

            if denominator != 0:
                final_rank = test_mean_val + (numerator / denominator)
                final_rank = float(np.asscalar(np.array(final_rank)) if isinstance(final_rank, np.ndarray) else final_rank)  # 确保 final_rank 是一个标量
                final_rank = final_rank.item() if isinstance(final_rank, np.ndarray) else final_rank
                final_rank = int(round(final_rank, 0))

                final_rank = min(max(final_rank, 1), 5)
                output.append([row[0], row[1], final_rank])
            else:
                output.append([row[0], row[1], 3])
                

    return output


In [464]:
pearson_5 = weighted_rating_pearson_correlation(test5, 201, pearson_top_k_5, pearson_matrix_5,pearson_test_5_means,pearson_train_means, arr,100)


In [465]:
pearson_10 = weighted_rating_pearson_correlation(test10, 301, pearson_top_k_10, pearson_matrix_10,pearson_test_10_means,pearson_train_means, arr, 80)


In [466]:
pearson_20 = weighted_rating_pearson_correlation(test20, 401, pearson_top_k_20, pearson_matrix_20,pearson_test_20_means,pearson_train_means, arr, 150)


In [ ]:
write_to_file(pearson_5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\my_pearson_k100_result5.txt')
write_to_file(pearson_10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\my_pearson_k150_result10.txt')
write_to_file(pearson_20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\my_pearson_k150_result20.txt')

In [ ]:
#Pearson with IUF

In [238]:
print(arr)
print(arr.shape)

[[5. 3. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [5. 4. 0. ... 0. 0. 0.]]
(200, 1000)


In [239]:
#Calculating the number of movie that has non_zero ratings
def cal_count_training_non_zero():
    movie_ratings_count = [0] * 1000
    # 遍历每个用户的电影评分
    for user_ratings in arr:
        # 遍历每个电影的评分
        for movie_index, rating in enumerate(user_ratings):
            # 如果评分不为0，增加对应电影的评分次数
            if rating != 0:
                movie_ratings_count[movie_index] += 1
    # 打印电影评分次数列表的长度
    print("Length of No_Zero_Ratings_Movie Count: " + str(len(movie_ratings_count)))
    
    return movie_non_zero_ratings_count

In [241]:
#Returns an array of iuf values for each training user
def cal_iuf_train_arr(movie_non_zero_ratings_count):
    iuf_train_arr = []
    for i in range(len(movie_non_zero_ratings_count)):
        if movie_non_zero_ratings_count[i] != 0:
            iuf_rating = math.log10((200/movie_non_zero_ratings_count[i]))
        else:
            iuf_rating = 1
        iuf_train_arr.append(iuf_rating)
    print("Length of iuf_training_array: " + str(len(iuf_train_arr)))
    return iuf_train_arr

In [246]:
#Returns the training matrix with each rating = rating * IUF value
def applied_iuf_train_matrix(training_data, iuf_training_vals):
    
    adjusted_training_data = training_data.copy()
    for user_index, user_ratings in enumerate(adjusted_training_data):
        for movie_index, rating in enumerate(user_ratings):
            if rating != 0:
                adjusted_training_data[user_index][movie_index] *= iuf_training_vals[movie_index]
    
    return adjusted_training_data

In [252]:
#Return the final IUF_training matrix(200x1000)

def final_iuf_train_arr():
    movie_non_zero_ratings_count = cal_count_training_non_zero()
    iuf_train_arr = cal_iuf_train_arr(movie_non_zero_ratings_count)
    #print(iuf_train_arr)

    training_data = arr.copy()
    training_data = training_data.astype(float)
    
    adjusted_training_data = applied_iuf_train_matrix(training_data, iuf_train_arr)
    print("Rows of final_iuf_train_data: " + str(len(adjusted_training_data)))
    print("Cols of final_iuf_train_data: " + str(len(adjusted_training_data[0])))
    return iuf_training_data

iuf_training_data = final_iuf_train_arr()

Length of No_Zero_Ratings_Movie Count: 1000
Length of iuf_training_array: 1000
Rows of final_iuf_train_data: 200
Cols of final_iuf_train_data: 1000


In [253]:
iuf_pearson_5_user_arr = test5_user_arr.copy()
iuf_pearson_10_user_arr = test10_user_arr.copy()
iuf_pearson_20_user_arr= test20_user_arr.copy()

In [476]:
#Calculating the movie counts for the test data

def cal_count_test_non_zero(test_user_arr):
    test_movie_rating_count = [0] * 1000
    for key in test_user_arr:
        for index,rating in enumerate(test_user_arr[key]):
            if rating != 0:
                test_movie_rating_count[index] += 1
    return test_movie_rating_count

test_5_movie_ratings_count = cal_count_test_non_zero(iuf_pearson_5_user_arr)
test_10_movie_ratings_count = cal_count_test_non_zero(iuf_pearson_10_user_arr)
test_20_movie_ratings_count = cal_count_test_non_zero(iuf_pearson_20_user_arr)

print("Length of test_5_movie_rating_counts: " + str(len(test_5_movie_ratings_count)))
print("Length of test_10_movie_rating_counts: " + str(len(test_10_movie_ratings_count)))
print("Length of test_20_movie_rating_counts: " + str(len(test_20_movie_ratings_count)))

Length of test_5_movie_rating_counts: 1000
Length of test_10_movie_rating_counts: 1000
Length of test_20_movie_rating_counts: 1000


In [264]:
#Returns an array of iuf values for each active user(test_data)

def cal_iuf_test_arr(test_movie_rating_count):
    iuf_test_arr = []
    for i in range(len(test_movie_rating_count)):
        if test_movie_rating_count[i] != 0:
            iuf_rating = math.log10((200/test_movie_rating_count[i]))
        else:
            iuf_rating = 1
        iuf_test_arr.append(iuf_rating)
    return iuf_test_arr


In [265]:

iuf_test_5_arr = cal_iuf_test_arr(test_5_movie_ratings_count)
iuf_test_10_arr = cal_iuf_test_arr(test_10_movie_ratings_count)
iuf_test_20_arr = cal_iuf_test_arr(test_20_movie_ratings_count)

print("Length of iuf_test5_vals: " + str(len(iuf_test_5_arr)))
print("Length of iuf_test10_vals: " + str(len(iuf_test_10_arr)))
print("Length of iuf_test20_vals: " + str(len(iuf_test_20_arr)))

Length of iuf_test5_vals: 1000
Length of iuf_test10_vals: 1000
Length of iuf_test20_vals: 1000


In [275]:
#Returns the test matrix with each rating = rating * IUF value

def apply_iuf_to_test_data(test_user_dict, iuf_values):
    for user_id, ratings in test_user_dict.items():
        adjusted_ratings = [rating * iuf_values[movie_index] if rating != 0 else 0 
                            for movie_index, rating in enumerate(ratings)]
        test_user_dict[user_id] = adjusted_ratings




In [276]:
# 调用函数更新测试用户评分字典
apply_iuf_to_test_data(iuf_pearson_5_user_arr, iuf_test_5_arr)
apply_iuf_to_test_data(iuf_pearson_10_user_arr, iuf_test_10_arr)
apply_iuf_to_test_data(iuf_pearson_20_user_arr, iuf_test_20_arr)


In [289]:
iuf_pearson_train_arr, iuf_pearson_train_means = calculate_pearson_adjusted_ratings(iuf_training_data)

print("The rows of iuf_train_pearson_arr: " + str(len(iuf_pearson_train_arr)))
print("The cols of iuf_train_pearson_arr: " + str(len(iuf_pearson_train_arr[0])))
print("The length of iuf_train_pearson_means: " + str(len(iuf_pearson_train_means)))

The rows of iuf_train_pearson_arr: 200
The cols of iuf_train_pearson_arr: 1000
The length of iuf_train_pearson_means: 200


In [290]:
iuf_pearson_test_5_arr,iuf_pearson_test_5_means = calculate_pearson_adjusted_ratings_for_test(iuf_pearson_5_user_arr)
iuf_pearson_test_5_arr,iuf_pearson_test_10_means = calculate_pearson_adjusted_ratings_for_test(iuf_pearson_10_user_arr)
iuf_pearson_test_5_arr,iuf_pearson_test_20_means = calculate_pearson_adjusted_ratings_for_test(iuf_pearson_20_user_arr)

print("The length of iuf_pearson_test_5_means: " + str(len(iuf_pearson_test_5_means)))
print("The length of iuf_pearson_test_10_means: " + str(len(iuf_pearson_test_10_means)))
print("The length of iuf_pearson_test_20_means: " + str(len(iuf_pearson_test_20_means)))
#print(iuf_pearson_5_user_arr)
#print(iuf_pearson_test_5_means)

The length of iuf_pearson_test_5_means: 100
The length of iuf_pearson_test_10_means: 100
The length of iuf_pearson_test_20_means: 100


In [293]:
iuf_pearson_cos_sim_matrix_5 = pd.DataFrame()
iuf_pearson_cos_sim_matrix_10 = pd.DataFrame()
iuf_pearson_cos_sim_matrix_20 = pd.DataFrame()

iuf_pearson_cos_sim_matrix_5 = create_cos_sim_matrix(iuf_pearson_cos_sim_matrix_5, iuf_pearson_5_user_arr, iuf_pearson_train_arr)
iuf_pearson_cos_sim_matrix_10 = create_cos_sim_matrix(iuf_pearson_cos_sim_matrix_10, iuf_pearson_10_user_arr, iuf_pearson_train_arr)
iuf_pearson_cos_sim_matrix_20 = create_cos_sim_matrix(iuf_pearson_cos_sim_matrix_20, iuf_pearson_20_user_arr, iuf_pearson_train_arr)


In [295]:
iuf_pearson_top_k_5 = top_k_sim(iuf_pearson_cos_sim_matrix_5)
iuf_pearson_top_k_10 = top_k_sim(iuf_pearson_cos_sim_matrix_10)
iuf_pearson_top_k_20 =top_k_sim(iuf_pearson_cos_sim_matrix_20)

print("Rows: " + str(len(iuf_pearson_top_k_5)) + ", Cols:" + str(len(iuf_pearson_top_k_5[0])))
print("Rows: " + str(len(iuf_pearson_top_k_10)) + ", Cols:" + str(len(iuf_pearson_top_k_10[0])))
print("Rows: " + str(len(iuf_pearson_top_k_20)) + ", Cols:" + str(len(iuf_pearson_top_k_20[0])))

Rows: 100, Cols:200
Rows: 100, Cols:200
Rows: 100, Cols:200


In [520]:
iuf_pearson_output5 = weighted_rating_pearson_correlation(test5, 201, iuf_pearson_top_k_5,iuf_pearson_cos_sim_matrix_5, pearson_test_5_means,pearson_train_means, arr,100)


In [521]:
iuf_pearson_output10 = weighted_rating_pearson_correlation(test10, 301, iuf_pearson_top_k_10,iuf_pearson_cos_sim_matrix_10,pearson_test_10_means,pearson_train_means, arr,80)


In [550]:
iuf_pearson_output20 = weighted_rating_pearson_correlation(test20, 401, iuf_pearson_top_k_20,iuf_pearson_cos_sim_matrix_20,pearson_test_20_means,pearson_train_means, arr,150)


In [439]:
write_to_file(iuf_pearson_output5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf\\my_iuf_pearson_k150_result5.txt')
write_to_file(iuf_pearson_output10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf\\my_iuf_pearson_k150_result10.txt')
write_to_file(iuf_pearson_output20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf\\my_iuf_pearson_k150_result20.txt')

In [312]:
#Pearson with case modification

In [314]:
print(pearson_test_5_means)
#print(iuf_pearson_test_5_means)

[4.8, 3.6, 3.8, 3.6, 3.2, 4.0, 3.8, 4.0, 4.2, 3.2, 3.8, 4.2, 4.0, 4.6, 4.0, 3.8, 3.4, 3.2, 4.8, 4.0, 4.4, 3.4, 3.4, 4.0, 3.4, 3.6, 4.2, 3.8, 3.0, 3.6, 3.4, 3.0, 3.8, 4.2, 3.6, 4.0, 4.4, 3.6, 3.8, 4.0, 3.4, 2.6, 4.4, 4.2, 2.2, 2.6, 4.2, 3.8, 3.2, 4.0, 2.2, 3.4, 3.0, 3.2, 3.2, 3.0, 4.2, 3.4, 2.6, 4.0, 2.4, 4.0, 3.0, 4.2, 3.2, 4.0, 4.6, 4.4, 4.6, 3.2, 4.0, 4.2, 3.4, 4.0, 3.6, 2.8, 4.2, 4.0, 3.4, 4.0, 4.2, 3.6, 3.8, 4.6, 2.6, 3.2, 3.8, 3.4, 3.8, 2.6, 3.0, 3.6, 3.6, 3.8, 3.8, 2.6, 3.0, 3.2, 4.6, 3.6]
[0.0, 0.0, 0.0, 8.881784197001253e-17, 0.0, 0.0, 0.0, -4.4408920985006264e-17, 0.0, -7.105427357601002e-16, -1.7763568394002506e-16, 0.0, 0.0, 0.0, -2.2204460492503132e-17, 0.0, -8.881784197001253e-17, 3.552713678800501e-16, 0.0, 0.0, 0.0, -1.7763568394002506e-16, 0.0, 0.0, 0.0, -1.7763568394002506e-16, 0.0, 0.0, 3.552713678800501e-16, 0.0, 4.4408920985006264e-17, 3.552713678800501e-16, 1.7763568394002506e-16, -3.552713678800501e-16, -1.7763568394002506e-16, -8.881784197001253e-17, 2.6645352591

In [484]:
'''
Returns the original cosine matrix with rating = rating * abs(rating)^1.5
Matrix Dimensions: 100x1000
'''
def case_modification_cos_sim_matrix(cos_sim_matrix):
    for index,row in enumerate(cos_sim_matrix):
        for index2,cos_sim_val in enumerate(row):
            cos_sim_matrix[index][index2] = cos_sim_matrix[index][index2] * (math.pow(abs(cos_sim_matrix[index][index2]),1.5))
    return cos_sim_matrix

case_modification_cos_sim_matrix_5 = pearson_matrix_5.copy()
#case_modification_cos_sim_matrix_5 = iuf_pearson_cos_sim_matrix_5.copy()
#case_modification_cos_sim_matrix_10 = iuf_pearson_cos_sim_matrix_10.copy()
#case_modification_cos_sim_matrix_20= iuf_pearson_cos_sim_matrix_20.copy()
#print(case_modification_cos_sim_matrix_5)
case_modification_cos_sim_matrix_10 = pearson_matrix_10.copy()
case_modification_cos_sim_matrix_20 = pearson_matrix_20.copy()

case_modification_cos_sim_matrix_5 = case_modification_cos_sim_matrix(case_modification_cos_sim_matrix_5)
#print(case_modification_cos_sim_matrix_5)
case_modification_cos_sim_matrix_10 =case_modification_cos_sim_matrix(case_modification_cos_sim_matrix_10)
case_modification_cos_sim_matrix_20 = case_modification_cos_sim_matrix(case_modification_cos_sim_matrix_20)

In [485]:
case_modification_pearson_top_k_5 = top_k_sim(case_modification_cos_sim_matrix_5)
case_modification_pearson_top_k_10 = top_k_sim(case_modification_cos_sim_matrix_10)
case_modification_pearson_top_k_20 = top_k_sim(case_modification_cos_sim_matrix_20)

print(len(case_modification_pearson_top_k_5))
print(len(case_modification_pearson_top_k_10))
print(len(case_modification_pearson_top_k_20))

100
100
100


In [481]:
#iuf_case_mod_pearson_output5 = weighted_rating_pearson_correlation(test5, 201, case_modification_pearson_top_k_5, case_modification_cos_sim_matrix_5, pearson_test_5_means,pearson_train_means, arr,120)
case_mod_pearson_output5 = weighted_rating_pearson_correlation(test5, 201, case_modification_pearson_top_k_5, case_modification_cos_sim_matrix_5, pearson_test_5_means,pearson_train_means, arr,100)
write_to_file(case_mod_pearson_output5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\case_mod\\my_case_mod_pearson_k100_result5.txt')
#write_to_file(iuf_case_mod_pearson_output5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf_case_mod\\my_iuf_case_mod_pearson_k120_result5.txt')

In [482]:
#iuf_case_mod_pearson_output10 = weighted_rating_pearson_correlation(test10, 301, case_modification_pearson_top_k_10, case_modification_cos_sim_matrix_10, pearson_test_10_means,pearson_train_means, arr,80)
#write_to_file(iuf_case_mod_pearson_output10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf_case_mod\\my_iuf_case_mod_pearson_k80_result10.txt')
case_mod_pearson_output10 = weighted_rating_pearson_correlation(test10, 301, case_modification_pearson_top_k_10, case_modification_cos_sim_matrix_10, pearson_test_10_means,pearson_train_means, arr,80)
write_to_file(case_mod_pearson_output10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\case_mod\\my_case_mod_pearson_k80_result10.txt')

In [483]:
#iuf_case_mod_pearson_output20 = weighted_rating_pearson_correlation(test20, 401, case_modification_pearson_top_k_20, case_modification_cos_sim_matrix_20, pearson_test_20_means,pearson_train_means, arr,150)
#write_to_file(iuf_case_mod_pearson_output20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\iuf_case_mod\\my_iuf_case_mod_pearson_k150_result20.txt')
case_mod_pearson_output20 = weighted_rating_pearson_correlation(test20, 401, case_modification_pearson_top_k_20, case_modification_cos_sim_matrix_20, pearson_test_20_means,pearson_train_means, arr,150)
write_to_file(case_mod_pearson_output20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\pearson\\case_mod\\my_case_mod_pearson_k150_result20.txt')

In [341]:
#Item based collaborative filtering

In [347]:
item_based_arr = arr.copy()
item_based_arr = item_based_arr.T

print(item_based_arr)
print("The row has "+str(len(item_based_arr))+" The Colomn has "+str(len(item_based_arr[0])))

[[5. 4. 0. ... 4. 1. 5.]
 [3. 0. 0. ... 0. 0. 4.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
The row has 1000 The Colomn has 200


In [348]:
def adjusted_cosine_similarity(ratings1, ratings2, active_user_mean):
    # 初始化相关变量
    filtered_ratings1 = []
    filtered_ratings2 = []
    numerator = 0
    sum_sq_diff1 = 0
    sum_sq_diff2 = 0
    
    # 过滤并计算所需的组件
    for rating1, rating2 in zip(ratings1, ratings2):
        if rating1 != 0 and rating2 != 0:
            diff1 = rating1 - active_user_mean
            diff2 = rating2 - active_user_mean
            filtered_ratings1.append(diff1)
            filtered_ratings2.append(diff2)
            numerator += diff1 * diff2
            sum_sq_diff1 += diff1 ** 2
            sum_sq_diff2 += diff2 ** 2
    
    # 处理特殊情况
    if not filtered_ratings1:  # 如果没有共同评分的用户
        return 0

    if len(filtered_ratings1) == 1:  # 如果只有一个共同评分的用户
        euclidean_distance = np.linalg.norm(filtered_ratings1[0] - filtered_ratings2[0])
        return 1 / (1 + euclidean_distance)
    
    # 计算余弦相似度
    denominator = np.sqrt(sum_sq_diff1 * sum_sq_diff2)
    if denominator == 0:
        return 0
    return numerator / denominator


In [350]:
test_5_item_based_means = pearson_test_5_means.copy()
test_10_item_based_means = pearson_test_5_means.copy()
test_20_item_based_means = pearson_test_5_means.copy()

print(test_5_item_based_means)
#print(test10_item_based_means)
#print(test20_item_based_means)

[4.8, 3.6, 3.8, 3.6, 3.2, 4.0, 3.8, 4.0, 4.2, 3.2, 3.8, 4.2, 4.0, 4.6, 4.0, 3.8, 3.4, 3.2, 4.8, 4.0, 4.4, 3.4, 3.4, 4.0, 3.4, 3.6, 4.2, 3.8, 3.0, 3.6, 3.4, 3.0, 3.8, 4.2, 3.6, 4.0, 4.4, 3.6, 3.8, 4.0, 3.4, 2.6, 4.4, 4.2, 2.2, 2.6, 4.2, 3.8, 3.2, 4.0, 2.2, 3.4, 3.0, 3.2, 3.2, 3.0, 4.2, 3.4, 2.6, 4.0, 2.4, 4.0, 3.0, 4.2, 3.2, 4.0, 4.6, 4.4, 4.6, 3.2, 4.0, 4.2, 3.4, 4.0, 3.6, 2.8, 4.2, 4.0, 3.4, 4.0, 4.2, 3.6, 3.8, 4.6, 2.6, 3.2, 3.8, 3.4, 3.8, 2.6, 3.0, 3.6, 3.6, 3.8, 3.8, 2.6, 3.0, 3.2, 4.6, 3.6]


In [351]:
#Creating a matrix with alredy rated movie lists for each active user
#test5(100x5)
#test10(100x10)
#test20(100x20)


def create_test_user_ratings_matrix(num_ratings, test_file):
    total_test_users_rated_movie_list = []
    user_rated_movies = []
    counter = 0
    
    for index,row in test_file.iterrows():
        if row[2] == 0:
            continue;

        movie_id = row[1]-1
        user_rated_movies.append((movie_id,row[2]))
        counter += 1
        if counter == num_ratings:
            total_test_users_rated_movie_list.append(user_rated_movies)
            counter = 0
            user_rated_movies = []
    return total_test_users_rated_movie_list



In [353]:
test_5_users_rated_movie_matrix =create_test_user_ratings_matrix(5, test5)
test_10_users_rated_movie_matrix = create_test_user_ratings_matrix(10, test10)
test_20_users_rated_movie_matrix = create_test_user_ratings_matrix(20, test20)

In [354]:
#Returns the indexes of the most similar movies in descending order

def item_based_top_k(indexes, k):
    top_k_indices = np.argsort(array)[-k:][::-1]
    return top_k_indices.tolist()

In [355]:
def item_based_weighted_ranking(test_ratings, rated_movies, item_means, ratings_data, offset, top_k):
    results = []

    for _, row in test_ratings.iterrows():
        if row[2] == 0:
            user_id = row[0] - offset
            target_movie_id = row[1] - 1

            cos_sim_weights = []
            for rated_movie in rated_movies[user_id]:
                weight = adjusted_cosine_similarity(ratings_data[rated_movie[0]], ratings_data[target_movie_id], item_means[user_id])
                cos_sim_weights.append(weight)

            if cos_sim_weights:
                # Get the indices of the top k similar items sorted by their similarity weight using the defined function
                top_indices = item_based_top_k(cos_sim_weights, top_k)
                
                numerator = 0
                denominator = 0
                for idx in top_indices:
                    weight = cos_sim_weights[idx]
                    if weight > 0.3:
                        rating = rated_movies[user_id][idx][1]
                        numerator += weight * rating
                        denominator += weight

                if denominator > 0:
                    predicted_rating = round(numerator / denominator)
                    predicted_rating = max(min(predicted_rating, 5), 1)
                else:
                    predicted_rating = 3  # Default rating if no suitable weights are found

                results.append([row[0], row[1], predicted_rating])

    return results



In [356]:
item_based_output_5 = item_based_weighted_ranking(test5, test_5_users_rated_movie_matrix ,test_5_item_based_means, item_based_arr, 201, 3)
write_to_file(item_based_output_5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\item_based\\item_based_0.3_k3_result5.txt')

In [357]:
item_based_output_10 = item_based_weighted_ranking(test10, test_10_users_rated_movie_matrix ,test_10_item_based_means, item_based_arr, 301, 5)
write_to_file(item_based_output_10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\item_based\\item_based_0.3_k5_result10.txt')

In [358]:
item_based_output_20 = item_based_weighted_ranking(test20, test_20_users_rated_movie_matrix ,test_20_item_based_means, item_based_arr, 401, 5)
write_to_file(item_based_output_20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\item_based\\item_based_0.3_k5_result20.txt')

In [359]:
#My Own Algorithm

In [551]:
#combine the above algorithms and give them different weight
'''

def my_own_method(cos_sim_res, pearson_res):  
    res = []
    for i in range(len(cos_sim_res)):
        #set cosine=0.5,pearson=0.2,iuf_pearson=0.2
        average = (cos_sim_res[i][2]*0.5) + (pearson_res[i][2]*0.4)
        average = int(round(average, 0))
        line = [cos_sim_res[i][0], cos_sim_res[i][1], average]
        res.append(line)
        line = []
    return res

'''
def my_own_method(cos_sim_res, pearson_res, iuf_pearson_res):  
    res = []
    for i in range(len(cos_sim_res)):
        #set cosine=0.5,pearson=0.2,iuf_pearson=0.2
        average = (cos_sim_res[i][2]*0.5) + (pearson_res[i][2]*0.2) + (iuf_pearson_res[i][2]*0.3) 
        average = int(round(average, 0))
        line = [cos_sim_res[i][0], cos_sim_res[i][1], average]
        res.append(line)
        line = []
    return res

In [552]:
my_own_method_5= my_own_method(output5, pearson_5,iuf_pearson_output5)

#my_own_method_5= my_own_method(output5, pearson_5)
#write_to_file(my_own_method_5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_method\\my_noiuf_method_result5.txt')

In [553]:
my_own_method_10= my_own_method(output10, pearson_10,iuf_pearson_output10)


In [554]:
my_own_method_20= my_own_method(output20, pearson_20,iuf_pearson_output20)


In [555]:
write_to_file(my_own_method_5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_method\\24_my_method_result5.txt')
write_to_file(my_own_method_10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_method\\24_my_method_result10.txt')
write_to_file(my_own_method_20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\my_method\\24_my_method_result20.txt')

In [474]:
#SVD Algorithm


In [368]:
#from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds
my_user_movie_matrix=df.copy()
# 选择保留的奇异值数量，通常需要根据数据集的大小和复杂性来调整
U, sigma, Vt = svds(my_user_movie_matrix, k=50)
sigma = np.diag(sigma)

# 计算所有用户对所有电影的预测评分
predicted_ratings = np.dot(np.dot(U, sigma), Vt)
# 设置输出文件路径
output_file_path = 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\svd_predicted_ratings.txt'

# 打开文件准备写入
with open(output_file_path, 'w') as file:
    # 遍历每个用户和每部电影
    for user_id in range(predicted_ratings.shape[0]):
        for movie_id in range(predicted_ratings.shape[1]):
            # 获取预测的评分，并四舍五入到最接近的整数
            rating = int(round(predicted_ratings[user_id, movie_id]))
            # 输出格式为：user movie rating
            file.write(f"{user_id + 1} {movie_id + 1} {rating}")
#predicted_ratings_df = pd.DataFrame(predicted_ratings, columns=range(1, user_movie_matrix.shape[1]+1))

#svd = TruncatedSVD(n_components=20)  # 假设我们选择20个潜在特征
#user_movie_matrix_reduced = svd.fit_transform(my_user_movie_matrix)
#predicted_ratings = svd.inverse_transform(user_movie_matrix_reduced)



In [477]:
from scipy.sparse.linalg import svds
def predict_ratings_svd(test_data, output_filename, shift_index):
    train_matrix=df.copy()
    U, sigma, Vt = svds(train_matrix, k=50)
    sigma = np.diag(sigma)
    all_predicted_ratings = np.dot(np.dot(U, sigma), Vt)

    with open(output_filename, 'w') as file:
        for index, row in test_data.iterrows():
            user_id = row[0]
            movie_id = row[1]
            rating = row[2]

            # 只对原本评分为0的电影进行预测
            if rating == 0:
                user_index = user_id - shift_index
                movie_index = movie_id - 1
                predicted_rating = round(all_predicted_ratings[user_index, movie_index])
                # 保证评分在1到5之间
                if predicted_rating < 1:
                    predicted_rating = 3  # 将不合理的低评分设置为中性评分3
                elif predicted_rating > 5:
                    predicted_rating = 5  # 将高于5的评分限制在5
                file.write(f"{user_id} {movie_id} {predicted_rating}\n")



In [478]:
'''
predict_ratings_svd(test5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k20_ratings_test5.txt',201)
predict_ratings_svd(test10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k20_ratings_test10.txt',301)
predict_ratings_svd(test20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k20ratings_test20.txt',40)

'''
# 调用函数
predict_ratings_svd(test5, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k5_ratings_test5.txt', 201)
predict_ratings_svd(test10, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k5_ratings_test10.txt', 301)
predict_ratings_svd(test20, 'E:\\文档\\AA-SCU\\272\\Proj 2\\results\\svd\\predicted_k5_ratings_test20.txt', 401)